#!/bin/dash -f
# Does not work with wmii-hg

wmiiscript=wmiirc # For wmii.sh
. wmii.sh

MODKEY=Mod4
UP=k
DOWN=j
LEFT=h
RIGHT=l
CLIENT_LAST="$(mktemp)"
CLIENT_THIS="$(mktemp)"
SLEEPLOCK="$(mktemp)"
noticetimeout=5
noticebar=/rbar/!notice

# Colors tuples: "<text> <background> <border>"
export WMII_NORMCOLORS='#4f4f4f #1c1c1c #1c1c1c'
export WMII_FOCUSCOLORS='#afd787 #1c1c1c #1c1c1c'
export WMII_BARCOLORS_NORMAL='#4f4f4f #1c1c1c #1c1c1c'
export WMII_BARCOLORS_FOCUS='#afd787 #1c1c1c #1c1c1c'
export WMII_FONT='xft:Terminus:size=7pt'
export WMII_TERM="x-terminal-emulator"
set -- $(echo $WMII_NORMCOLORS $WMII_FOCUSCOLORS)

if ! test -d "${WMII_CONFPATH%%:*}"; then
    mkdir "${WMII_CONFPATH%%:*}"
    res=$(wihack -type DIALOG xmessage -nearmouse -buttons Windows,Alt -print -fn $WMII_FONT \
          "Welcome to wmii,$wi_newline$wi_newline" \
          "Most of wmii's default key bindings make use of the$wi_newline" \
          "Windows key, or equivalent. For keyboards lacking such$wi_newline" \
          "a key, many users change this to the Alt key.$wi_newline$wi_newline" \
          "Which would you prefer?")
    [ "$res" = "Alt" ] && MODKEY=Mod1
    echo "MODKEY=$MODKEY" >"${WMII_CONFPATH%%:*}/wmiirc_local"
    chmod +x "${WMII_CONFPATH%%:*}/wmiirc_local"
fi

# Menu history
hist="${WMII_CONFPATH%%:*}/history"
histnum=5000

# Column Rules
wmiir write /colrules <<!
/gimp/ -> 17+83+41
/.*/ -> 62+38 # Golden Ratio
!

# Tagging Rules
wmiir write /tagrules <<!
/MPlayer|VLC|gwaei|mplayer2/ -> ~
/Firefox|Nightly|Vimprobable2|Luakit/ -> web
/Claws-mail|Thunderbird|Mail/ -> mail
/Geeqie/ -> geeqie
/Pidgin|Xchat/ -> chat
!

# Status Bar Info
status() {
	echo -n  $(/home/$USER/.wmii/wmii-weather.cache.sh) '|' $(cpufreq-info -fm) $(sensors | sed -n -e '3{p;q}' | cut -d' ' -f9) '|' $(acpitool -ba|gawk '/Battery/ {printf "%s ",$5}; /AC adapter/ {print $4};'|sed 's/\,//g') '|' $(date +"%a %b %d %H:%M")
}

local_events() { true;}
wi_runconf -s wmiirc_local

echo $WMII_BARCOLORS_NORMAL | wmiir create $noticebar

# Event processing
events() {
	cat <<'!'
# Events
Event ClientFocus
    if [ -s "$CLIENT_THIS" ]; then
        cat $CLIENT_THIS > $CLIENT_LAST
    fi
    echo "$@" > $CLIENT_THIS
Event CreateTag
	echo "$WMII_BARCOLORS_NORMAL" "$@" | wmiir create "/lbar/$@"
Event DestroyTag
	wmiir remove "/lbar/$@"
Event FocusTag
	wmiir xwrite "/lbar/$@" "$WMII_BARCOLORS_FOCUS" "$@"
Event UnfocusTag
	wmiir xwrite "/lbar/$@" "$WMII_BARCOLORS_NORMAL" "$@"
Event UrgentTag
	shift
	wmiir xwrite "/lbar/$@" "*$@"
Event NotUrgentTag
	shift
	wmiir xwrite "/lbar/$@" "$@"
Event LeftBarClick LeftBarDND
	shift
	wmiir xwrite /ctl view "$@"
Event Unresponsive
	{
		client=$1; shift
		msg="The following client is not responding. What would you like to do?$wi_newline"
		resp=$(wihack -transient $client \
			      xmessage -nearmouse -buttons Kill,Wait -print
			      -fn "${WMII_FONT%%,*}" "$msg $(wmiir read /client/sel/label)")
		if [ "$resp" = Kill ]; then
			wmiir xwrite /client/$client/ctl slay &
		fi
	}&
Event Notice
	wmiir xwrite $noticebar $wi_arg

	kill $xpid 2>/dev/null # Let's hope this isn't reused...
	{ sleep $noticetimeout; wmiir xwrite $noticebar ' '; }&
	xpid = $!

# Menus
Menu Client-3-Delete
	wmiir xwrite /client/$1/ctl kill
Menu Client-3-Kill
	wmiir xwrite /client/$1/ctl slay
Menu Client-3-Fullscreen
	wmiir xwrite /client/$1/ctl Fullscreen on
Event ClientMouseDown
	wi_fnmenu Client $2 $1 &

Menu LBar-3-Delete
	tag=$1; clients=$(wmiir read "/tag/$tag/index" | awk '/[^#]/{print $2}')
	for c in $clients; do
		if [ "$tag" = "$(wmiir read /client/$c/tags)" ]; then
			wmiir xwrite /client/$c/ctl kill
		else
			wmiir xwrite /client/$c/tags -$tag
		fi
		if [ "$tag" = "$(wi_seltag)" ]; then
			newtag=$(wi_tags | awk -v't='$tag '
				$1 == t { if(!l) getline l
					  print l
					  exit }
				{ l = $0 }')
			wmiir xwrite /ctl view $newtag
		fi
	done
Event LeftBarMouseDown
	wi_fnmenu LBar "$@" &

# Actions
Action showkeys
	echo "$KeysHelp" | xmessage -file - -fn ${WMII_FONT%%,*}
Action quit
	wmiir xwrite /ctl quit
Action exec
	wmiir xwrite /ctl exec "$@"
Action rehash
	wi_proglist $PATH >$progsfile
Action status
	set +xv
	if wmiir remove /rbar/status 2>/dev/null; then
		sleep 2
	fi
	echo "$WMII_BARCOLORS_NORMAL" | wmiir create /rbar/status
	while status | wmiir write /rbar/status; do
		sleep 1
	done
Action mpdmon
    /home/$USER/.wmii/wmii-ncmpcpp.sh &
Action pdf
    mupdf "$(zenity --file-selection)" &
Action tmux
    bash /home/$USER/.wmii/tmuxatt.sh &
Action fetchmail
    killall -USR1 fetchmail &
    
# Key Bindings
KeyGroup XF86 and general environment
Key XF86AudioLowerVolume
    amixer -c 0 sset 'Master',0 1dB- &
Key XF86AudioRaiseVolume
    amixer -c 0 sset 'Master',0 1dB+ &
Key XF86AudioMute
    amixer -c 0 sset 'Master',0 0db &
Key XF86Sleep
    SLEEPLOCK_AGE="$(( $(date +%s)-$(stat -c %Z $SLEEPLOCK) ))"
    if [ $SLEEPLOCK_AGE -lt 30 ]; then
        eval xscreensaver-command -lock; qdbus --system org.freedesktop.UPower /org/freedesktop/UPower org.freedesktop.UPower.Suspend
        touch $SLEEPLOCK
    else
        notify-send "Won't sleep yet" "It has been < 30s since I last woke up." &
    fi 
Key $MODKEY-End
    xscreensaver-command -lock &
Key $MODKEY-F5
    gwaei &
Key $MODKEY-F6
    gjiten -v &
Key $MODKEY-Control-Return
    x-www-browser &
Key $MODKEY-Print
    scrot -d 5 -c -q 100 &
Key $MODKEY-F7
    eval $WMII_TERM -e alsamixer &
Key $MODKEY-F8
    eval $WMII_TERM -e alsamixer -Dequal &
Key $MODKEY-Tab
    dash /home/$USER/.wmii/wmii-clientmenu.sh &
Key $MODKEY-c
    eval notify-send -i /home/$USER/.icons/Clarity/scalable/apps/calc.svg "$(</dev/null wimenu -pbc | awk '{ print $0,"\n" }' | bc -l)" "" &
Key $MODKEY-x
    wmiir xwrite /tag/sel/ctl colmode sel +max &
Key $MODKEY-Escape
    if [ -s "$CLIENT_LAST" ]; then
        CLIENT_TARGET=$(wmiir ls /client | grep "$(cat $CLIENT_LAST)")
        if [ -n "$CLIENT_TARGET" ]; then
            TAG=$(wmiir read /client/${CLIENT_TARGET}tags | head -n1)
            wmiir xwrite /ctl view "$TAG"
            wmiir xwrite /tag/sel/ctl select client "${CLIENT_TARGET%%/}"
        fi
    else
        echo "" > "$CLIENT_LAST"
    fi
Key $MODKEY-Shift-Return
    /home/$USER/.wmii/wmii-tmuxspawn.sh &

KeyGroup MPD
Key $MODKEY-F1
    mpc toggle &
Key $MODKEY-F2
    mpc stop &
Key $MODKEY-F3
    mpc prev &
Key $MODKEY-F4
    mpc next &

KeyGroup Moving around
Key $MODKEY-$LEFT   # Select the client to the left
	wmiir xwrite /tag/sel/ctl select left
Key $MODKEY-$RIGHT  # Select the client to the right
	wmiir xwrite /tag/sel/ctl select right
Key $MODKEY-$UP     # Select the client above
	wmiir xwrite /tag/sel/ctl select up
Key $MODKEY-$DOWN   # Select the client below
	wmiir xwrite /tag/sel/ctl select down

Key $MODKEY-space   # Toggle between floating and managed layers
	wmiir xwrite /tag/sel/ctl select toggle

KeyGroup Moving through stacks
Key $MODKEY-Control-$UP    # Select the stack above
	wmiir xwrite /tag/sel/ctl select up stack
Key $MODKEY-Control-$DOWN  # Select the stack below
	wmiir xwrite /tag/sel/ctl select down stack

KeyGroup Moving clients around
Key $MODKEY-Shift-$LEFT   # Move selected client to the left
	wmiir xwrite /tag/sel/ctl send sel left
Key $MODKEY-Shift-$RIGHT  # Move selected client to the right
	wmiir xwrite /tag/sel/ctl send sel right
Key $MODKEY-Shift-$UP     # Move selected client up
	wmiir xwrite /tag/sel/ctl send sel up
Key $MODKEY-Shift-$DOWN   # Move selected client down
	wmiir xwrite /tag/sel/ctl send sel down
Key $MODKEY-Shift-space   # Toggle selected client between floating and managed layers
	wmiir xwrite /tag/sel/ctl send sel toggle

KeyGroup Moving through tags
Key $MODKEY-Left
    TAGLIST=$(wmiir ls /tag | grep -v sel)
    THIS_TAG="$(wmiir read /tag/sel/ctl | head -n1)/"
    LEFT=""
    for TAG in $TAGLIST; do
        if [ "$TAG" = "$THIS_TAG" ]; then
            if [ -n "$LEFT" ]; then
                wmiir xwrite /ctl view "$LEFT" &
                break
            fi
        else
            LEFT="$TAG"
        fi
    done
Key $MODKEY-Right
    TAGLIST=$(wmiir ls /tag | grep -v sel)
    THIS_TAG="$(wmiir read /tag/sel/ctl | head -n1)/"
    RIGHT=0
    for TAG in $TAGLIST; do
        if [ "$TAG" = "$THIS_TAG" ]; then
            RIGHT=1
        elif [ $RIGHT -eq 1 ]; then
            wmiir xwrite /ctl view "$TAG" &
            break
        fi
    done
    
KeyGroup Client actions
Key $MODKEY-f # Toggle selected client's fullsceen state
	wmiir xwrite /client/sel/ctl Fullscreen toggle
Key $MODKEY-Shift-c # Close client
	wmiir xwrite /client/sel/ctl kill
Key $MODKEY-Shift-x #xkill
    xkill &

KeyGroup Changing column modes
Key $MODKEY-d # Set column to default mode
	wmiir xwrite /tag/sel/ctl colmode sel default-max
Key $MODKEY-s # Set column to stack mode
	wmiir xwrite /tag/sel/ctl colmode sel stack-max
Key $MODKEY-m # Set column to max mode
	wmiir xwrite /tag/sel/ctl colmode sel stack+max

KeyGroup Running programs
Key $MODKEY-a      # Open wmii actions menu
	action $(wi_actions | wimenu -h "${hist}.actions" -n $histnum) &
Key $MODKEY-p      # Open program menu
	eval wmiir setsid "$(wimenu -p'$' -h "${hist}.progs" -n $histnum <$progsfile)" &
Key $MODKEY-Control-p # Run a program per gksu
    eval "wimenu -p'#' <$progsfile | xargs gksu -gS" &

Key $MODKEY-Return # Launch a terminal
	eval wmiir setsid $WMII_TERM &

KeyGroup Other
Key $MODKEY-Control-t # Toggle all other key bindings
	case $(wmiir read /keys | wc -l | tr -d ' \t\n') in
	0|1)
		echo -n "$Keys" | wmiir write /keys
		wmiir xwrite /ctl grabmod $MODKEY;;
	*)
		wmiir xwrite /keys $MODKEY-Control-t
		wmiir xwrite /ctl grabmod Mod3;;
	esac

KeyGroup Tag actions
Key $MODKEY-t       # Change to another tag
	(tag=$(wi_tags | wimenu -h "${hist}.tags" -n 50) && wmiir xwrite /ctl view $tag) &
Key $MODKEY-Shift-t # Retag the selected client
	c=$(wi_selclient)
	(tag=$(wi_tags | wimenu -h "${hist}.tags" -n 50) && wmiir xwrite /client/$c/tags $tag) &
!
	for i in 0 1 2 3 4 5 6 7 8 9; do
		cat <<!
Key $MODKEY-$i		 # Move to the numbered view
	wmiir xwrite /ctl view "$i"
Key $MODKEY-Shift-$i     # Retag selected client with the numbered tag
	wmiir xwrite /client/sel/tags "$i"
!
	done
}
wi_events events local_events

# WM Configuration
wmiir write /ctl <<!
	font $WMII_FONT
	focuscolors $WMII_FOCUSCOLORS
	normcolors $WMII_NORMCOLORS
	grabmod $MODKEY
	border 1
!

# Misc
progsfile="$(wmiir namespace)/.proglist"
action status &
wi_proglist "$PATH:/usr/sbin" >$progsfile &

# Setup Tag Bar
IFS="$wi_newline"
wmiir rm $(wmiir ls /lbar | sed 's,^,/lbar/,') >/dev/null
seltag=$(wmiir read /tag/sel/ctl | sed 1q)
unset IFS
wi_tags | while read tag
do
	if [ "$tag" = "$seltag" ]; then
		echo "$WMII_BARCOLORS_FOCUS" "$tag"
	else
		echo "$WMII_BARCOLORS_NORMAL" "$tag"
	fi | wmiir create "/lbar/$tag"
done

wi_eventloop
